### ISSUE TITLE
Nothing happens when I click on any of the wallets

### ISSUE THREAD

**Issue by pranav-singhal** [WalletConnect/web3modal-swift#16]
**Describe the bug**
I am trying to follow the example on `develop` branch. But when I click on any of the buttons for the available wallets, nothing happens (video attached)

**SDK Version**
 - Client: web3modal-swift
 - Version [e.g. 22]`develop`

**To Reproduce**
This is what my contentView looks like:

```
import SwiftUI
import Web3Modal
import WalletConnectSign



@main
struct RacoonProfileApp: App {
    init() {
        let projectId = "xxxx";
        let metadata = AppMetadata(
            name: "Web3Modal Swift Dapp",
            description: "Web3Modal DApp sample",
            url: "wallet.connect",
            icons: ["https://avatars.githubusercontent.com/u/37784886"]
        )
        
        Networking.configure(
            projectId: projectId,
            socketFactory: WalletConnectSocketClientFactory()
        )

        Web3Modal.configure(
            projectId: projectId,
            metadata: metadata
        )
    }
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}


```

And this is the body of the content view:

```
var body: some View {
        NavigationView {
            
            VStack {
                Button("Connect Wallet") {
                    Web3Modal.present()
                }
                .buttonStyle(W3MButtonStyle())
                
                Button("Select Network") {
                    Web3Modal.present()
                }
                .buttonStyle(W3MButtonStyle(variant: .accent, leftIcon: Image(systemName: "network")))
                
            }
        }
    }
```

**Video attached**

**Device (please complete the following information):**
 - Device: Iphone 14 pro max

https://github.com/WalletConnect/web3modal-swift/assets/29460541/7c3cf7a0-e688-472e-80a4-0fb9220a6335

**Additional context**

**Comment by tomav** [comment]
Same here.

**Comment by pranav-singhal** [comment]
Hey
Just following up here

**Comment by sennhann29** [comment]
0x8b9466aA9c536195E908a40225D41C246Db666a5

**Comment by Yokymia32** [comment]
Sources/Web3Modal/Core/BlockchainAPIInteractor.swift

**Comment by pranav-singhal** [comment]
@Yokymia32 is this file realted to the issue?
Can you add some context please?

**Comment by radeknovis** [comment]
Please try a more recent version like
https://github.com/WalletConnect/web3modal-swift/releases/tag/1.0.8
