### ISSUE TITLE
Support CocoaPods To Install Web3Modal

### ISSUE THREAD

**Issue by CagataySurf** [WalletConnect/web3modal-swift#27]
Is there any way to install web3modal with cocoapods ? Currently using swift package manager prevents us from using web3modal with our CI pipeline beause we use Unity game engine. Dependencies can be included with pods from unity but currently there is no api for adding dependencies to spm from unity.

**Comment by radeknovis** [comment]
Hey @CagataySurf, currently there is no way to use web3modal with cocoapods, however we are planning to add support for cocoapods, hopefully by the end of this month. 

Not sure what your exact use case is but you might want to know that we are also developing Web3Modal SDK for Unity. @skibitsky can tell you more if interested

**Comment by CagataySurf** [comment]
Thanks for the updates and web3modal unity sdk would help a lot. Since wallet connect v2 unity repo is not fully functional, we can't use it so we are using kotlin and swift repos to develop wallet connect implementations and plug them into unity. Which takes a lot of effort.

**Comment by skibitsky** [comment]
Hey @CagataySurf,

We are working on WalletConnectModal native implementation for Unity, it will be released soon along with the refactor of some parts of the WalletConnectUnity SDK. However, even in the current form, WalletConnectUnity should be functional.

Please open an issue in [WalletConnectUnity](https://github.com/WalletConnect/WalletConnectUnity) if something isn't working for you or if you have any questions. I would be happy to help!
