### ISSUE TITLE
Session disconnecting bug

### ISSUE THREAD

**Issue by chocoford** [WalletConnect/web3modal-swift#57]
**Describe the bug**
After manually calling `Web3Modal.instance.disconnect(topic: )` or `Web3Modal.instance.cleanup()`, `Web3Model.present()` still remains in a state where the wallet is logged in.

**SDK Version**
 - Client: Swift
 - Version 1.1.0

**To Reproduce**
Just disconnect a seesion with the code below:
```swift
Web3Modal.instance.disconnect(topic: ...)
```
Then calling `Web3Model.present()`, the wallet info is still being displayed.
But the output of `print(Web3Modal.instance.getSessions())` showing it is empty.

**Device (please complete the following information):**
 - Device: iPhone 15 pro
 - OS: iOS 17.3.1

**Comment by mooshee** [comment]
Bump

**Comment by llbartekll** [comment]
hey @chocoford could you upgrade the sdk to the latest? the issue seems resolved

**Comment by chocoford** [comment]
Hello @llbartekll , Yes the problem has gone after updating to `1.3.1`, thanks!

**Comment by llbartekll** [comment]
Great, closing then
