### ISSUE TITLE
[SPM] Cannot add version 1.3.1 as a Package Dependency

### ISSUE THREAD

**Issue by mooshee** [WalletConnect/web3modal-swift#61]
**Describe the bug**
Adding `https://github.com/WalletConnect/web3modal-swift` as a Package Dependency is unable to be resolved.

> Showing All Issues
Failed to resolve dependencies Dependencies could not be resolved because no versions of 'wallet-mobile-sdk' match the requirement 1.0.0..<2.0.0 and root depends on 'web3modal-swift' 1.3.1..<2.0.0.
'web3modal-swift' >= 1.3.1 practically depends on 'wallet-mobile-sdk' 1.0.0..<2.0.0 because no versions of 'web3modal-swift' match the requirement 1.3.2..<2.0.0 and 'web3modal-swift' 1.3.1 depends on 'wallet-mobile-sdk' 1.0.0..<2.0.0.

**SDK Version**
 - Client: Swift
 - Version: 1.3.1

**To Reproduce**
1. File Add Package Dependency
2. Enter this repo's url `https://github.com/WalletConnect/web3modal-swift`
3. Tap Add Package
4. See Error

**Comment by llbartekll** [comment]
hey @mooshee, does your app depend on wallet-mobile-sdk independently from web3modal?

**Comment by mooshee** [comment]
No

**Comment by llbartekll** [comment]
Just created a clean project to try to reproduce and I didn't experience any issues at all. 
maybe try to remove derived data and clean build folder.

**Comment by mooshee** [comment]
I've tried doing a clean and package reset. I'll try the fresh project and report back.

**Comment by mooshee** [comment]
@llbartekll Looks good now. Thanks!
