### ISSUE TITLE
Error running Swift example project

### ISSUE THREAD

**Issue by citruslab** [WalletConnect/web3modal-swift#63]
**The problem:**
Hello! I'm trying to run the Web3Modal Swift example project but I get these Auth Token creation errors in Xcode's console. What am I missing? 🙏  I'm building to my iPhone and entered walletconnect project ID in configuration file. The app runs on the device, then the console returns:

---------------------------------------------------------------------------------
---------- 🧊 Atlantis is running (version 1.24.0)
---------- Github: https://github.com/ProxymanApp/atlantis
---------------------------------------------------------------------------------
[Atlantis] Looking for Proxyman app in the network...
Auth token creation error: OSStatus: -34018, message: A required entitlement isn't present.
Auth token creation error: OSStatus: -34018, message: A required entitlement isn't present.
Socket connection status: disconnected
Socket connection status: disconnected
Auth token creation error: OSStatus: -34018, message: A required entitlement isn't present.
Auth token creation error: OSStatus: -34018, message: A required entitlement isn't present.
connectionFailed
Socket connection status: disconnected

**Expected behavior**
Connection should succeed.

**Screenshots**
<img width="1728" alt="Screenshot 2024-03-20 at 8 02 47 AM" src="https://github.com/WalletConnect/web3modal-swift/assets/29637180/b3849abf-58f4-4ecf-abf3-a2b1969a5716">
<img width="1728" alt="Screenshot 2024-03-20 at 8 03 08 AM" src="https://github.com/WalletConnect/web3modal-swift/assets/29637180/ed5b7d07-7bfc-44d1-9478-89663045535c">
<img width="1728" alt="Screenshot 2024-03-20 at 8 03 32 AM" src="https://github.com/WalletConnect/web3modal-swift/assets/29637180/adc40ceb-0298-490e-a1b9-caa8cb3f0181">

**Device (please complete the following information):**
 - Device: iPhone Pro 14
 - OS: iOS 17.3.1
 - Xcode 15
 - macOS 14.3.1

**Comment by mooshee** [comment]
@citruslab you need to add the App Group capability and pass it into the web3modal config, otherwise it can't write to the same space.

**Comment by citruslab** [comment]
Thank you @mooshee it now connects fine after making those changes. Thanks for your time :)

Is there an example for implementing walletConnect in a macOS app?
